#pragma once

#include "groupcmd.h"

#pragma pack (push)
#pragma pack (1)

enum CLIENT_OPRATION
{
	CO_NEXT_INFINITY =1,
	CO_LEAVE_INFINITY,
	CO_FULL_STRENGTH,
	CO_SURRENDER_COPY,
	CO_GET_DAILY_LOGIN_PRIZE,
	CO_GET_LEVEL_PRIZE,
	CO_GET_LOGIN_GOLD_PRIZE,
	CO_CALL_OPPONENT,
	CO_SERVER_OPEN_SEND_FLOWER_FORM,
	CO_SERVER_OPEN_INFINITY_FAIL_FORM,
	CO_SERVER_OPEN_HEIMUYA_FORM,
	CO_SERVER_OPEN_QUEST_INSTANCE_FORM,
	CO_MAX,
};

enum
{
	SEND_LOGIN_PRIZE,
	CLIENT_UTILITY_OPERATION,
	SEND_OPEN_INFINITY_CHALLAGEN_MENU,
	REQUEST_JOIN_NEW_INSTANCE,
	ONLINE_PRIZE,
	REQUEST_GET_CURRENT_ONLINE_PRIZE,
	SEND_LOGIN_DAYS_COUNT,
	SEND_LOGIN_GOLD_PRIZE,
	SERVER_COMP_HIDE_CFG,
	CLOSE_CHALLENGE_MENU,
	REQUEST_JOIN_QUEST_INSTANCE,
	SEND_JUMP_OUT_QUEST_INSTANCE,
	REQUEST_GET_QUEST_INSTANCE_AWARD,
	REQUEST_LEAVE_QUEST_INSTANCE,
};

struct CHARACTER2_SEND_JUMP_OUT_QUEST_INSTANCE_Data
{
	int nItem1;
	int nItem2;
	int nItem3;
};

struct CHARACTER2_CLIENT_UTILITY_OPERATION_Data
{
	int nId;
	int nParam;
};

struct CHARACTER2_SEND_OPEN_INFINITY_CHALLAGEN_MENU_Data
{
	int nExp;
	int nMoney;
	char szItemName[32];
	BYTE nItemColor;
	BYTE nRound;
	bool bFirst;
};

struct CHARACTER2_REQUEST_JOIN_NEW_INSTANCE_Data 
{
	int nIndex;
};

struct CHARACTER2_REQUEST_JOIN_QUEST_INSTANCE_Data 
{
	int nIndex;
};

struct CHARACTER2_ONLINE_PRIZE_Data
{
	int nCurPrize;
	DWORD dwTime;
};

struct CHARACTER2_SEND_LOGIN_PRIZE_Data 
{
	int nPrize[3];
};

struct CHARACTER2_SEND_LOGIN_DAYS_COUNT_Data 
{
	int nDays;
};

struct CHARACTER2_SERVER_COMP_HIDE_CFG_Data 
{
	char szForm[10][32];
	char szComp[10][32];
};

#pragma pack (pop)