#ifndef _LOG_STRUCT_H
#define _LOG_STRUCT_H

#define _ACTION_SAVE

/************************************************************************/
/* 如果需要新增加枚举，请插到最后，不要插到枚举中间                     */
/************************************************************************/

enum
{
	ACTION_LOGIN,
	ACTION_LOGOUT,
	ACTION_JUMP,
	ACTION_LEVELUP,
	ACTION_BANK_INC_MONEY,
	ACTION_BANK_DEC_MONEY,
	ACTION_STALLAGE_BEGIN,
	ACTION_STALLAGE_END,
	ACTION_CONF_CREATE,
	ACTION_CONF_JOIN,
	ACTION_CONF_LEAVE,
	ACTION_CONF_CHANGEJOB,
	ACTION_DELETE,
	ACTION_ENGAGE_MARRY,
	ACTION_UNENGAGE_MARRY,
	ACTION_MARRY,
	ACTION_UNMARRY_FORCE,
	ACTION_UNMARRY_PROTOCOL,
	ACTION_CHECK_PASS_SUCCESSFUL,
	ACTION_CHECK_PASS_FAILED,
	ACTION_RESET_PASS,
	ACTION_JUMP_MAP,
	ACTION_START_AUTO,
	ACTION_STOP_AUTO,
	ACTION_PRETRANSFER_PLAYER,
	ACTION_CANCEL_PRETRANSFER_PLAYER,
	ACTION_TRANSFER_PLAYER_END,
	ACTION_GM_BLOCK,//GM 封号
	ACTION_SET_FIGHT_MODE,
	ACTION_SET_HEIMUYA,
	ACTION_ADD_NEWFRIEND,
	ACTION_NEW_LUCKBOX,
	ACTION_MAX,
};

enum AddExpType 
{
	EXP_FROM_NULL,
	EXP_FROM_KILL_ENEMY,
	EXP_FROM_KILL_PLAYER,
	EXP_FROM_COMPLETE_QUEST,
	EXP_FROM_RUN_SCRIPT,
	EXP_FROM_DIE,
	EXP_FROM_WAR,
	EXP_FROM_NOW,
	EXP_FROM_ROSE,
	EXP_FROM_HOMESKILL,
	EXP_FROM_MAX,
};

enum AddSkillExpType 
{
	SKILL_EXP_FROM_KILL_ENEMY,
	SKILL_EXP_FROM_COMPLETE_QUEST,
	SKILL_EXP_FROM_RUN_SCRIPT,
	SKILL_EXP_FROM_NOW,
	SKILL_EXP_FROM_MAX,
};

enum AddGoldType
{
	GOLD_FROM_NULL,
	GOLD_FROM_PICK_UP,			//捡取
	GOLD_FROM_COMPLETE_QUEST,	//任务
	GOLD_FROM_RUN_SCRIPT,		//脚本
	GOLD_FROM_TRADE,			//交易
	GOLD_FROM_SHOP,				//商店
	GOLD_FROM_STALLAGE,			//摆摊
	GOLD_FROM_WAR,				//战场
	GOLD_FROM_CREATE_HOME,		//创建帮会
	GOLD_FROM_MANAGE_HOME,		//管理帮会
	GOLD_FROM_REBUILD_HOME,		//帮会自荐
	GOLD_FROM_MSG,				//发送信息
	GOLD_FROM_LEVEL_UP,			//升级
	GOLD_FROM_STORAGE,			//仓库
	GOLD_FROM_SLAVE_RENAME,		//宠物重命名
	GOLD_FROM_REPAIR,			//修理
	GOLD_FROM_NOW,				//当前金钱
	GOLD_FROM_SAYCOUNTRY,		//国家聊天
	GOLD_FROM_MOHUA,			//装备魔化
	GOLD_FROM_SMELT,			//装备强化
	GOLD_FROM_AUCTION,			//拍卖
	GOLD_FROM_ACCEPT_QUEST,		//接收任务
	GOLD_FROM_TREASURE_BOX,		//宝箱
	GOLD_FROM_GET_PAY,			//领取俸禄
	GOLD_FROM_MAIL,				//商城
	GOLD_FROM_PANSHI,			//叛师
	GOLD_FROM_QUTU,				//驱徒
	GOLD_FROM_SLAVE_EVOLUTION,	//宠物进化
	GOLD_FROM_SLAVE_MAINATTRIB_SYNCRETIZE,	//宠物主属性融血
	GOLD_FROM_SLAVE_SUBATTRIB_SYNCRETIZE,	//宠物副属性融血
	GOLD_FROM_SLAVE_DIVINATORYVALUE_SYNCRETIZE,	//宠物卦象融血
	GOLD_FROM_SLAVE_REVIVE,		//宠物复活
	GOLD_FROM_ADDSKILLEXP,		//增加技能经验
	GOLD_FROM_ITEM_TRANSFER,	//装备属性转移
	GOLD_FROM_LOOTBIAO,			//跑镖
	GOLD_FROM_SLAVE_EXTENDUP,	//宠物强化
	GOLD_FROM_SLAVE_PHASEUP,	//宠物进阶
	GOLD_FROM_AUCTION_COST,		//拍卖价值
	GOLD_FROM_MAIL_COST,		//商城价值
	GOLD_FROM_ADD_COUNTRY_GOLD,	//增加国家资金
	GOLD_FROM_LUA,
	GOLD_FROM_BUYSOLD,          //回购
	GOLD_FROM_HOME_JUANQIAN,
	GOLD_FROM_GEMUPGRADE,
	GOLD_FROM_GEMSPLITE,
	GOLD_FROM_SKILL,
	GOLD_FROM_EQUIPHOLE,
	GOLD_FROM_EQUIPGEMADD,
	GOLD_FROM_EQUIPGEMREMOVE,
	GOLD_FROM_MATERIALUPGRADE,
	GOLD_FROM_PKDEATH,
	GOLD_FROM_MAKE,				//合成,
	GOLD_FROM_GM,
	GOLD_FROM_ONLINE,
	GOLD_FROM_HOMEBILL,
	GOLD_FROM_TRANSPORT,
	GOLD_FROM_LEVELUPHOLE,
	GOLD_FROM_NEWSTALLAGE,     //离线摆摊
	GOLD_FROM_SHOUGOU,         //离线摆摊中的收购 预扣
	GOLD_FROM_BUYSHOUGOU,      //其他玩家买了收购物品扣的钱
	GOLD_FROM_SHOUGOUCANCEL,   //取消收购
	GOLD_FROM_SLAVE_PK,
	GOLD_FROM_ADD_MESSAGE,     //20000
	GOLD_FROM_GUESS,
	GOLD_FROM_LOGIN,
	GOLD_FROM_COPY,
	GOLD_FROM_HORSE,
	GOLD_FROM_DAILY_LOGIN,
	GOLD_FROM_SEND_FLOWER_BACK,
	GOLD_FROM_SEND_FLOWER,
	GOLD_FROM_MAX,
};

enum AddFlowerType
{
	FLOWER_FROM_NULL,
	FLOWER_FROM_RUN_SCRIPT,
	FLOWER_FROM_NOW,
	FLOWER_FROM_SHOP,
	FLOWER_FROM_COMPLETE_QUEST,
	FLOWER_FROM_MSG,
	FLOWER_FROM_MAX,
};

enum SlaveLogType
{
	SLAVE_LOG_NULL,
	SLAVE_LOG_GET_FROM_CAPTURE,	//捕获
	SLAVE_LOG_GET_FROM_ITEM,	//物品获得
	SLAVE_LOG_RELEASE,			//释放
	SLAVE_LOG_TRADE,			//交易获得
	SLAVE_LOG_WASH_SINGLE_QUALITY,	//洗点
	SLAVE_LOG_LEVEL_UP,		//升级
	SLAVE_LOG_ADD_SKILL,	//加技能
	SLAVE_LOG_REMOVE_SKILL,	//删技能
	SLAVE_LOG_GET_FROM_HULU,	//葫芦里招
	SLAVE_LOG_DIE,			//死亡
	SLAVE_LOG_EXTEND_UP,	//扩展属性升级
	SLAVE_LOG_PHASE_UP,		//进阶
	SLAVE_LOG_DEAD_FROM_EVOLUTION,	//进化删除
	SLAVE_LOG_BORN_FROM_EVOLUTION,	//进化出生
	SLAVE_LOG_DEAD_FROM_MAINATTRIB_SYNCRETIZE,	//主属性溶血失败
	SLAVE_LOG_DEAD_FROM_SUBATTRIB_SYNCRETIZE,	//副属性溶血失败
	SLAVE_LOG_NEWFUSE_FAILD,	//宠物融合失败
	SLAVE_LOG_MAINATTRIB_SYNCRETIZE,		//主属性成功
	SLAVE_LOG_SUBATTRIB_SYNCRETIZE,			//副属性成功
	SLAVE_LOG_NEWFUSE,	//宠物融合
	SLAVE_LOG_WASH_SINGLE_GROW,			//重置宠物成长
	SLAVE_LOG_WASH_QUALITY_AND_LEVEL,	//重置属性和等级
	SLAVE_LOG_WASH_SINGLE_DIVINATORY,	//重置卦阵属性
	SLAVE_LOG_NEW_REVIVE,
	SLAVE_LOG_BIND,
	SLAVE_LOG_UNBIND,
	SLAVE_LOG_CANCEL_UNBIND,
	SLAVE_LOG_UNBIND_END,
	SLAVE_LOG_BORN_FROM_PROTEROZOIC,	//源生兽
	SLAVE_LOG_EXTEND_UP_FAILED,			//扩展属性升级失败
	SLAVE_LOG_PHASE_UP_FAILED,			//进阶失败
	SLAVE_LOG_BEFEED,
	SLAVE_LOG_FUSED,			//附身
	SLAVE_LOG_TRADE_OUT,               //交易出去
	SLAVE_LOG_FEED,
	SLAVE_LOG_BAITAN,          //摆摊
	SLAVE_LOG_TRANS,
	SLAVE_LOG_MAX,
};

enum AuctionType
{
	AUCTION_BY_GOLD,						//元宝拍卖
	AUCTION_BY_MONEY,						//金币拍卖
	GOLD_AUCTION,							//拍卖元宝,
	SYS_AUCTION,
};

enum AuctionActionType
{
	ADD_ITEM_AUCTION,								//添加拍卖物品
	JOIN_BUY,							//加入竞拍
	OVERSTEP_BUY,						//竞拍被超出
	FAID_AUCTION,							//流拍
	SELL_SUCCESS,							//成功卖出物品或者元宝
	BUY_SUCCESS,							//成功拍得
};

#endif