#pragma once

#pragma pack (push)
#pragma pack (1)

enum EMAP_COPY_CMD
{
	MAP_COPY_CMD_USER_JOIN_MAP,
	MAP_COPY_CMD_USER_LEAVE_MAP,

	MAP_COPY_CMD_RESPONSE_GET_INSTANCE_STATUS	= 5,
 	MAP_COPY_CMD_RESPONSE_CREATE_INSTANCE,
	MAP_COPY_CMD_RESPONSE_INIT_INSTANCE,
 	MAP_COPY_CMD_RESPONSE_JOIN_INSTANCE,
	MAP_COPY_CMD_USER_MAX,
};

typedef struct MAP_COPY_CMD_MAP_COPY_CMD_USER_JOIN_MAP_Data
{
	int nMapIndex;
}MAP_COPY_CMD_MAP_COPY_CMD_USER_LEAVE_MAP_Data;

struct MAP_COPY_CMD_MAP_COPY_CMD_RESPONSE_GET_INSTANCE_STATUS_Data
{
	int nMapCopyId;
	int nPlanSize;
	int pnPlanData[1];
};

typedef struct MAP_COPY_CMD_MAP_COPY_CMD_RESPONSE_CREATE_INSTANCE_Data
{
	int nMapCopyId;
	int nResult;
}MAP_COPY_CMD_MAP_COPY_CMD_RESPONSE_JOIN_INSTANCE_Data,
MAP_COPY_CMD_MAP_COPY_CMD_RESPONSE_INIT_INSTANCE_Data;

#pragma pack (pop)