/* DO NOT EDIT THIS FILE - it is machine generated */
#include "GlobalDefine.h"
#ifdef USE_ANDROID
#include <jni.h>
/* Header for class com_mejoygame_rpgwar_JniCall */

#ifndef _Included_com_mejoygame_rpgwar_JniCall
#define _Included_com_mejoygame_rpgwar_JniCall
#ifdef __cplusplus
extern "C" {
#endif
	void	Java_com_mejoygame_rpgwar_JniCall_OpenForm(JNIEnv*  env, jobject thiz, jstring szForm,bool bOpen);
	void	Java_com_mejoygame_rpgwar_JniCall_SetLoginStep(JNIEnv*  env, jobject thiz,int nStep);
	void	Java_com_mejoygame_rpgwar_JniCall_SetLoginMID(JNIEnv*  env, jobject thiz,int nStep);
	void	Java_com_mejoygame_rpgwar_JniCall_SetToken(JNIEnv*  env, jobject thiz,jstring szForm);
#ifdef __cplusplus
}
#endif
#endif
#endif